version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres-template
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '5000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: pnpm run start:dev
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - db
